import React, { useState } from 'react'
import {useNavigate} from "react-router-dom"

function HookCounter2() {

    const [count, setCount] = useState(0)
    const navigate = useNavigate(
      
    )

  return (
    <div>
        Count : {count}
        <button onClick={()=> setCount(0)}>Reset</button>
        <button onClick={()=> setCount(prevCount => prevCount+1)}>Increment</button>
        <button onClick={()=> setCount(count-1)}>Decrement</button>
        <button onClick={() =>navigate('order-summary', {replace: true})}>Place order</button>
        <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non tellus dapibus, aliquam dolor id, tincidunt arcu. Donec cursus massa est, eget porttitor arcu ullamcorper in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel urna finibus felis ultricies cursus in pharetra odio. Donec vel massa ac mauris feugiat laoreet vel eget nibh. Fusce sagittis, nulla dictum cursus feugiat, dui ex pulvinar ante, vel congue nisi orci vitae metus. Integer felis ante, vehicula non dui eu, sagittis scelerisque tortor. Quisque finibus, nunc et tempor semper, sem orci vulputate metus, in cursus diam quam faucibus ipsum. Quisque viverra metus sed libero feugiat, ac commodo justo laoreet. Ut et ornare nibh. Nullam hendrerit, metus et sollicitudin placerat, nulla mi ullamcorper ante, id sollicitudin dui lorem vitae ligula. Praesent iaculis, elit non pellentesque vulputate, enim massa ultricies dolor, eget consequat erat metus eu tortor. Curabitur ornare nisl quis justo condimentum, in porta ex viverra.

Nunc sit amet commodo arcu. Sed ornare lectus sit amet congue blandit. Curabitur justo enim, hendrerit eget fringilla et, consequat vel sapien. Nulla quis efficitur risus. Fusce malesuada nisi nibh, sed fermentum risus hendrerit a. Phasellus non cursus turpis. Vestibulum vulputate, est at condimentum ornare, est arcu lobortis orci, in rhoncus mauris libero at ex. Duis lacinia nunc lorem, quis eleifend ipsum tincidunt a. Aliquam quis tempus nisl. Sed augue nibh, viverra sit amet ultrices aliquet, consectetur vel diam. Cras quis vehicula lacus. Etiam consectetur magna nibh, eget sodales est pellentesque quis. Integer vel semper urna.

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam ultrices tortor rhoncus eros vestibulum, feugiat feugiat ligula sollicitudin. Suspendisse potenti. Nulla at arcu ex. Praesent elementum nec nunc semper ultrices. Nunc at sapien interdum, faucibus nisi nec, blandit diam. Praesent et lectus semper mi euismod maximus. Suspendisse potenti. Suspendisse eu suscipit felis. Quisque vitae nisl in lacus sodales rhoncus id eu quam. Maecenas sodales quis tortor efficitur dictum. Nunc maximus rhoncus erat, ut cursus libero iaculis sit amet. Nulla eu ultricies enim, in ullamcorper diam. Fusce mauris diam, dictum sed libero ac, volutpat ornare neque. Nulla tempus malesuada turpis vel posuere.

Duis rhoncus justo et aliquam luctus. Cras nec mi nisl. Sed vehicula urna sed vulputate tempus. Ut a accumsan sem. In elementum tristique dolor, quis ultricies purus iaculis et. Aenean vel dui sodales, sodales enim ac, pharetra nunc. In sed tellus ornare, molestie nibh vel, vestibulum ipsum. Vivamus molestie nulla nibh, in dignissim justo hendrerit quis. Aliquam at placerat eros.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vestibulum felis in augue ornare, a finibus lectus finibus. Ut vel volutpat nibh. Aliquam ut vulputate arcu, quis sodales purus. Cras imperdiet dapibus elit, id scelerisque tellus sagittis et. Sed vehicula tempus molestie. Pellentesque vestibulum, velit sit amet luctus scelerisque, lectus nisl imperdiet augue, ac porttitor eros nisl id justo. Mauris sodales erat nec ligula aliquam hendrerit. Donec non lacus at odio condimentum euismod. Phasellus ornare hendrerit pulvinar. Aenean pulvinar ex neque, non porttitor turpis pellentesque nec. Praesent tempor justo ac turpis sollicitudin lacinia. Nam vel luctus odio, sed pharetra ligula.

Duis in aliquet enim. Etiam tincidunt ante ac ligula porttitor auctor. Vestibulum luctus in lorem at sagittis. Praesent in scelerisque nisl. Maecenas consequat eleifend aliquam. Proin purus nulla, aliquam vitae lectus ac, auctor sollicitudin ipsum. Mauris ut dolor nec nunc ullamcorper dapibus. Curabitur vel urna sit amet odio rutrum consectetur ut eget ante. Aliquam erat volutpat. Curabitur turpis leo, mollis quis magna sodales, consectetur consectetur felis. Sed cursus lectus a nisi maximus, et hendrerit velit rutrum.

Sed elementum, mi vitae vehicula luctus, ligula ante congue nisi, at malesuada libero libero id mauris. Donec ultrices euismod purus, ac porttitor ex dapibus in. Integer eu laoreet risus. Morbi et ultrices diam. Nullam sit amet interdum sapien, a iaculis nulla. Aliquam vitae erat tellus. Suspendisse mattis lectus id felis ullamcorper pretium. Aliquam tempus, augue sed gravida ultricies, orci justo varius nibh, interdum molestie ante mauris et tellus.

Aenean dignissim leo vel tellus iaculis laoreet. Proin eu rhoncus dolor. Praesent scelerisque vulputate enim, volutpat sollicitudin purus porta a. Aenean congue risus quis libero egestas, vitae scelerisque sem hendrerit. Quisque placerat nulla et eleifend faucibus. Pellentesque sit amet tristique urna. Nulla posuere tempor magna, a tincidunt purus scelerisque in. Integer ut ex viverra, scelerisque elit ut, eleifend metus. Mauris tristique tristique suscipit. Vestibulum lorem nibh, dapibus vitae sapien eu, congue mattis purus. Nulla non maximus dui, aliquam elementum metus. Suspendisse blandit metus et lacus malesuada, ut tempus metus consequat. Aliquam non sapien eu tellus luctus congue nec ut urna.

Sed mattis leo id quam dapibus varius. Curabitur semper urna vel accumsan facilisis. Curabitur vel mollis enim. Vestibulum id porta sem, sit amet venenatis nisl. Maecenas non consequat arcu. Ut ornare ipsum ac magna iaculis pharetra. Phasellus mattis laoreet turpis, non dictum diam consequat vel. Sed in pulvinar urna, sed feugiat sem. Integer semper, lectus sit amet laoreet imperdiet, tortor sem ornare quam, quis elementum neque orci non sem. Curabitur sed scelerisque dui.

Donec vitae orci tempus, scelerisque ligula eget, congue magna. Curabitur vestibulum tortor sed quam convallis pretium. Aenean justo dui, mollis ut mi a, porttitor efficitur lacus. Nulla facilisi. Phasellus eros orci, tristique sit amet venenatis vel, faucibus ut sem. Praesent ultricies ex vel iaculis convallis. Ut tempus mi interdum turpis commodo, in lobortis lectus ullamcorper. Suspendisse lacus odio, euismod maximus nisi at, vulputate tempor est. Curabitur aliquet cursus congue. Vestibulum eu tortor tortor. Aenean pulvinar, dui sit amet feugiat suscipit, velit neque elementum ligula, eget consequat dui ligula ut ligula. Ut finibus felis nec diam egestas vehicula. Ut rhoncus vel urna sed elementum.

Ut dapibus ipsum ac magna viverra, sed tempus purus bibendum. Nunc at auctor nunc. Suspendisse lacinia venenatis ligula, id molestie augue pulvinar ut. Ut at imperdiet enim, at facilisis felis. Aliquam eu luctus quam, vitae euismod nibh. Sed et sapien tincidunt, posuere velit vitae, viverra metus. Cras tempus pulvinar justo, malesuada egestas eros sodales sed. Nam consequat iaculis risus non posuere. Aliquam vitae lacus non ligula tempus tincidunt. Mauris vitae lorem blandit, dictum elit eu, luctus justo.

Vestibulum porttitor tempor interdum. Maecenas accumsan ex at dolor suscipit lacinia. Curabitur vel velit aliquet, rhoncus enim sed, gravida orci. In sollicitudin sit amet risus sed rhoncus. Nam a sapien convallis, hendrerit metus vel, accumsan tortor. Nam ornare odio urna, vitae placerat risus accumsan non. Duis consectetur enim sit amet dui dictum suscipit. Nam et vulputate sapien. Etiam auctor mi sed nisi malesuada, eu imperdiet ipsum tempus. Mauris sed lacinia lectus, eget vulputate justo.

Cras euismod sem id lacus posuere, eu accumsan nibh convallis. Sed faucibus suscipit sodales. Quisque laoreet diam diam, eget viverra lorem ultricies quis. Sed aliquam rutrum venenatis. Cras non sapien a augue condimentum euismod sed at metus. Praesent vel efficitur tellus. In hac habitasse platea dictumst. Donec tellus augue, porttitor vel turpis sit amet, auctor pellentesque nisl. Donec lacus velit, porta vel euismod in, bibendum eget ante.

Duis felis nisl, rutrum ac augue quis, facilisis commodo tortor. Integer congue blandit diam, eu congue lorem interdum a. Donec tincidunt euismod metus eget laoreet. Morbi arcu mi, faucibus a odio ac, tempus vehicula quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed ac quam tempor, vehicula justo sed, sollicitudin felis. Nunc nec nibh a nulla laoreet suscipit sed ac leo. Quisque molestie ligula a ex vehicula, sed fringilla quam porta. Ut dapibus ut urna at euismod. Aenean porttitor id orci vel malesuada. Suspendisse pharetra diam in pellentesque semper. In consectetur non leo euismod accumsan. Vivamus quis justo volutpat, molestie sem vel, vehicula dolor. Proin scelerisque augue sed arcu elementum, quis elementum diam luctus. Vivamus non est eget urna varius maximus. Mauris cursus orci at justo consectetur, sed fermentum libero vulputate.

Suspendisse pretium dignissim odio vel tempor. Nam nec pellentesque augue. Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at lobortis lorem. Suspendisse eleifend lectus nibh, ut sollicitudin orci pretium eget. Fusce aliquet eros ut vehicula elementum. Quisque in justo euismod, suscipit sapien eget, tempus ante. Suspendisse ut faucibus mi, nec feugiat lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis dapibus elit et vestibulum rhoncus. In eget pulvinar ex. Suspendisse interdum dapibus odio.

Nam eget faucibus tortor, a consectetur purus. Aliquam laoreet lacus libero, nec scelerisque velit blandit ac. Maecenas id elit ut arcu ullamcorper eleifend. Sed placerat euismod lacus. Mauris quis tortor ac felis euismod interdum. Nunc nec urna quam. Nullam eget iaculis lacus, nec dignissim augue. Nam pulvinar bibendum dui in placerat. Phasellus neque ex, dictum vitae mi at, pulvinar ultricies est. Sed massa augue, semper in turpis vel, aliquet rhoncus nulla. Aliquam erat volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas in mattis tortor, eu consequat ante. Quisque sed sem urna. Vivamus commodo et sem nec mollis.

Mauris congue tempus lorem eu laoreet. Nunc ut est nec nibh convallis elementum. Vivamus sed velit fringilla, sagittis velit ac, auctor ipsum. Pellentesque iaculis sollicitudin mollis. Vivamus semper cursus quam ultrices tincidunt. Nunc ac nibh id nisl lobortis tristique ac a neque. Sed luctus nulla id orci aliquet, nec consectetur dolor tristique. Nunc congue ligula sit amet ex varius, vel tristique nulla pharetra. Quisque eget enim enim. Suspendisse eu libero ultrices, ultrices ipsum volutpat, tempor odio. Sed laoreet sed enim posuere porttitor. Nulla tempus volutpat ex, ut commodo augue aliquet ac. Aenean sed elit eleifend, placerat diam nec, elementum ante. Pellentesque ac convallis lorem, in tincidunt ex. Praesent sollicitudin turpis nulla, ut faucibus sapien aliquam porttitor.

Duis laoreet, risus eget mattis tempor, sapien dolor placerat nibh, sed sodales diam ipsum sed libero. Vivamus suscipit leo eget sapien commodo, a hendrerit lectus fermentum. Aliquam suscipit, ligula non condimentum lobortis, diam orci pellentesque ligula, sit amet sollicitudin metus mi at eros. Nulla in arcu purus. Nunc sed justo sed sapien gravida mollis. Aenean pellentesque consequat est sit amet aliquam. Nam vestibulum tempor eros a tincidunt. Maecenas a turpis vel elit gravida aliquet. Nunc lacus lectus, tincidunt nec tempus et, sagittis in leo. In semper mi ac neque consequat, in iaculis libero fringilla. Sed convallis sagittis vulputate. Pellentesque ultrices nibh id dui consequat scelerisque. Praesent faucibus commodo ultricies. Sed nibh nibh, ultricies et pretium eget, sollicitudin sed est.

Sed vehicula nibh nec scelerisque maximus. Sed et orci luctus, eleifend est posuere, blandit neque. Morbi eget lorem in odio pretium commodo. Sed urna metus, rutrum ac fringilla a, bibendum id elit. Morbi id consequat dolor. Quisque viverra, velit in congue mollis, metus nisi molestie diam, id varius quam est ac libero. Aenean vulputate, lectus vel tempor gravida, massa odio eleifend lorem, quis pharetra leo dui ac dolor. In hac habitasse platea dictumst. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec non metus id elit rhoncus malesuada. Nulla lacinia neque ac ante pharetra euismod.

Phasellus tempus leo non scelerisque hendrerit. Praesent egestas turpis mauris, et efficitur massa aliquam in. Nulla facilisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus et facilisis orci, sit amet fermentum neque. Nulla ullamcorper fringilla libero at porta. Phasellus sit amet posuere tellus. Morbi feugiat urna id pretium iaculis. Phasellus ultricies pharetra orci auctor scelerisque. Pellentesque placerat sed metus quis cursus. Duis id viverra elit. Maecenas accumsan erat ultrices, lobortis mi at, consequat lacus.
        </div>

    </div>
  )
}

export default HookCounter2
